# =============================================================================
# Dovecot main configuration
# =============================================================================

# Enable protocols
protocols = imap lmtp

# Log to stderr for Docker
log_path = /dev/stderr
info_log_path = /dev/stdout

# Include conf.d
!include conf.d/*.conf
